lib/food-generator.js
lib/index.js
lib/keyboard-tracker.js

* Collision detection added for players moving to the edges of the canvas. Stops player at edge.
Closes #5

Boundary collision added

---

lib/index.js
lib/keyboard-tracker.js
lib/player.js
lib/shape-drawer.js

@jwperry @Jpease1020 closes #2, also moves player constructor and prototype methods out of index.js.

Player refactored to own js file

---

lib/food-generator.js
lib/index.js
lib/player.js

* Added collision detection for player and food. If food center point is within player's spherical radius, it is eaten.
* Added function to replace food as it is eaten.
Closes #8, #9, #10, #11

8 collision exact overlap

---

test/index.js
test/player-eats-food-test.js

Adds a test for a player to eat a piece of food. 
Adds tests for a player moving toward food, and eats it if it's in range but does not eat it of it is not in range.

adds tests for a player eating food

---

lib/player.js

closes #26 
Used the partial applications we learned this morning to clean up the move function. Also extracted a ton of the logic so it's way more readable/simple now. Check it out @jwperry @Jpease1020

Refactor player move

---

lib/index.js
lib/player.js
test/index.js
test/players-eat-each-other-test.js

1.  Adds first implementation of players eating each other and tests for it.

14 collision players eat players and grow

---

public/online-player.js
server.js

closes #53  Players are now re-spawning after dying and players that are small may fly into the sphere of a large player and are eaten quickly.

changed logic to make a small player more eatable

---

index.html
lib/food-generator.js
lib/game-packager.js
lib/player.js
public/client.js
public/index.html
public/online-player.js
server.js

Closes #49 #58 
* Adds support for larger canvas size.
* Refactored loop logic for stability and improved frame rate.
* Added some error handlers.
* Added extra step to client-server handshake for client initialization.
* Adds zoom factor to change zoom level of view as player grows in size.
* Several small refactors.

49 larger canvas

---

lib/game-packager.js
public/client.js
public/index.html
public/jscolor.js
public/main.bundle.js
public/online-player.js
public/style.css
public/test.bundle.js
server.js

Players can now submit a name and color.

Player names

---

public/client.js
server.js

Closes #57 
* Disconnect bug is fixed. Players array was being erroneously assigned to result of .splice().

57 fixing disconnect crash bug

---

public/client.js
public/index.html

- adds a leader board that dynamically updates showing the largest player at the top
- need to add styling to the page to make it better visually for the user
- I had to reverse the players array again before it sorted properly.

adds a leader board showing biggest player at the top

---

lib/food-generator.js
lib/food.js
lib/game-packager.js
lib/speed-boost.js
lib/virus.js
public/client.js
public/main.bundle.js
public/online-player.js
server.js

Closes #36 
Closes #44 
Closes #67 
* Refactors.
* Adds viruses.
* Game balance tweaks to spawn caps and speed.
* Adds Player names on-screen.
* Caps scale on player names.

44 viruses

---

public/client.js
public/index.html
public/style.css

ready for review @jwperry @Jpease1020

Basic styling done

---

public/client.js
server.js

Closes #71 
* Fixes size of name scaling.
* Cap introduced.

71 fix name scaling bug

---

server.js

- I reorganized the server file to make it easier to read.
- organized the global variables together at the top of the screen
- organized the function declarations at the bottom of the screen
- pulled out some of the logic in the game loop into separate methods for clarification / readability

reorganizes the server file for readability

---

public/client.js

adds score which is the players mass to the leader board

---

lib/food-generator.js
lib/open-coordinates.js

- Takes randOnCanvas out of food generator so it's available for using in other places in code base
- Renames file to more appropriate name (feel free to comment on this and make suggestions as I am not crazy about the name @jecrockett , @jwperry  or anything else you see)

takes randOnCanvas out of food gen

---

public/online-player.js
server.js
test/game-packager-test.js
test/player-eats-food-test.js

Closes #90 
* Player speed is now only updated in one place, in server.js before the player moves.

Speed is now updated only in server.js before moving player

---

test/open-coordinates-test.js

- unit test for openCoordinates not creating coordinates inside a player

Unit test open coordinates

---

lib/food-generator.js
lib/virus.js
public/client.js
public/online-player.js
server.js

Closes #79 
Closes #97 
* The first virus now slowly gravitates toward the largest player.
* Virus locations now shuffle every 5 minutes to avoid stagnation.
* Player start positions and respawn positions are random.
* Slight refactors.

canvas attribute bug fixed

---

public/client.js
public/index.html
public/style.css

More styling

---

lib/food-generator.js

replaces while loops with if statements to regen food/viruses/boosts
closes #74

Replaces while blocks for food generation

---

lib/open-coordinates.js

Removes the second check we had on !isNotInsidePlayer

refactor check for spawning food outside of players

---

test/food-generator-test.js
test/game-packager-test.js

* Fixes minor test issues due to refactors.

Fixing tests

---

lib/player.js

- removes the distance being calculated in every function where a player is eating an object of any type

refactors coliision distance

---

test/virus-test.js

Closes #113 
* Adds movement testing on virus model.

Additional virus movement testing

---

lib/player.js
public/client.js
public/index.html
public/test.bundle.js
test/player-eats-food-test.js
test/player-eats-speed-boost-test.js
test/player-movements-test.js

@jwperry @Jpease1020 Changed user input over to arrow keys. Prevented the default action if pressed so it doesn't scroll up/down anymore. Updated all tests so they're all passing with the updated keys.

Change user input to arrow keys, update tests -- all pass

---

lib/player.js
public/client.js
public/index.html
public/style.css
test/player-movements-test.js

Good idea on allowing them to choose. Added functionality for both sets of inputs. Also re-added tests that show WASD work as inputs and made one more to show hitting both inputs in the same direction doesn't double up movement. @jwperry @Jpease1020

Arrow key input

---

public/style.css

The free hosted background image used expired This adds a new one.

Replaces expired background image link
